name: Annulla ultimo commit

on: [push]


jobs:
  revert:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        token: ${{ secrets.WORKFLOW_TOKEN }}

    - name: Configura Git
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'

    - name: Annulla ultimo commit
      run: |
        git revert HEAD --no-edit
        git push origin HEAD:master
