name: Manual Undo Push Action
on: 
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to undo commit'
        required: true
        default: 'master'

jobs:
  Undo:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout code
        uses: actions/checkout@v2
      - name: undo
        run: |
          ls -a
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git reset --hard HEAD~1
          git push --force
